DROP DATABASE IF EXISTS projeto_mt4;
CREATE DATABASE projeto_mt4;

USE projeto_mt4;

CREATE TABLE TIPO (
	id INT NOT NULL AUTO_INCREMENT,
	nome VARCHAR(50) NOT NULL,
	PRIMARY KEY(id)
);

CREATE TABLE DISPOSITIVO (
	id INT NOT NULL AUTO_INCREMENT,
	hostname VARCHAR(50) NOT NULL,
	ip INT UNSIGNED NOT NULL,
	tipo_id INT NOT NULL,
	fabricante VARCHAR(50) NOT NULL,
	PRIMARY KEY (id)
);

ALTER TABLE DISPOSITIVO ADD CONSTRAINT FOREIGN KEY (tipo_id) REFERENCES TIPO (id);